home/urls.py
from django.urls import path

from . import views

urlpatterns = [

    path('', views.home, name='home'),
]

product/product_urls/urls.py
from django.urls import path

from ..views import product_list

urlpatterns = [

    # companies/{company_slug}/{category_slug}/{subcategory_slug}/
    path('<str:subcategory_slug>/', product_list, name='product-list'),

]

product/subcategory_urls/urls.py
from django.urls import path, include

from ..views import subcategory_list

urlpatterns = [

    # companies/{company_slug}/{category_slug}/
    path('<str:category_slug>/', subcategory_list, name='subcategory-list'),

    # companies/{company_slug}/{category_slug}/{subcategory_slug}/
    path('<str:category_slug>/', include('product.product_urls.urls')),
]

product/urls.py
from django.urls import path, include

from . import views

urlpatterns = [

    # companies/
    path('', views.company_list, name='company-list'),

    # companies/{company_slug}/
    path('<str:slug>/', views.category_list, name='category-list'), 

    # companies/{company_slug}/{category_slug}/
    path('<str:comapny_slug>/', include('product.subcategory_urls.urls')),

]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from product.custom_admin.views import get_category, get_subcategory

# custom 404 error page
handler404 = 'home.views.custom_page_not_found_view'

urlpatterns = [
    # admin
    path('admin/', admin.site.urls),
    
    # home
    path('', include(('home.urls', 'home'), namespace='home')),

    # about
    path('about/', include(('about.urls', 'about'), namespace='about')),

    # product
    path('companies/', include(('product.urls', 'product'), namespace='product')),

    # product category dropdown
    path('getCategory/', get_category, name='category'), 

    # product subcategory dropdown
    path('getSubcategory/', get_subcategory, name='subcategory'),

    # client
    path('clients/', include(('client.urls', 'client'), namespace='client')),

    # contact
    path('contact/', include(('contact.urls', 'contact'), namespace='contact')),


]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/custom_admin/forms.py
from django import forms

from product.models import Category, Subcategory, Product

class ProductAdminFormMixin(forms.ModelForm):
    """
    Product admin model form mixin.
    """
    class Meta:
        model  = Product
        fields = ['company', 'category', 'subcategory']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['category'].queryset = Category.objects.none()
        
        if 'company' in self.data:
            try:
                company_id = int(self.data.get('company'))
                self.fields['category'].queryset = Category.objects.filter(company_id=company_id).order_by('name')
            except (ValueError, TypeError):
                pass
        elif self.instance.pk:
            self.fields['category'].queryset = self.instance.company.categories.order_by('name')          

class ProductFilterForm(ProductAdminFormMixin, forms.ModelForm):
    """
    Product admin filter model form.
    """
    category = forms.ModelChoiceField(queryset=Category.objects.all(), required=False) 
    
    class Meta:
        model  = Product
        fields = ['company', 'category']


class SubcategoryAdminForm(forms.ModelForm):
    """
    Subcategory admin model form.
    """    
    class Meta:
        model  = Subcategory
        fields = ['name', 'company', 'category']

product/custom_admin/views.py
import json
from django.shortcuts import render
from django.http import HttpResponse

from product.models import Category, Subcategory

def get_category(request): 
    """
    Take request and return json data of a list of filtered categories according to the selected company. 
    """
    print("hey")
    company_id = request.GET.get('id', '') 
    print(company_id)
    category_lst = list(Category.objects.filter(company_id=int(company_id)).values('id', 'name')) 
    return HttpResponse(json.dumps(category_lst), content_type="application/json") 


def get_subcategory(request):
    """
    Take request and return json data of a list of filtered subcategories according to the selected category. 
    """
    print("hey1")
    category_id = request.GET.get('id', '') 
    print(category_id)
    subcategory_lst = list(Subcategory.objects.filter(category_id=int(category_id)).values('id', 'name')) 
    return HttpResponse(json.dumps(subcategory_lst), content_type="application/json") 

product/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator
from django.db.models import Q

from .models import Company, Category, Subcategory, Product

def company_list(request):
    """
    Display the companies list.
    """
    # get a queryset of all the companies
    companies = Company.objects.all()

    categories, subcategories, products = None, None, None
    page_obj_category, page_obj_subcategory, page_obj_product = None, None, None
    page_number = request.GET.get('page')
    # Search by company name, category, subcategory, product name, model, or code.
    query = request.GET.get('q')
    if query:
        companies = Company.objects.filter(name__icontains=query) 
        categories = Category.objects.filter(name__icontains=query)
        subcategories = Subcategory.objects.filter(name__icontains=query)
        products = Product.objects.filter(
            Q(name__icontains=query)|
            Q(model__icontains=query)|
            Q(code__icontains=query)
        ).distinct() 

    # paginate the companies list
    paginator_company = Paginator(companies, 12) # display 8 companies per page.
    page_obj_company = paginator_company.get_page(page_number)
    
    if categories:
        # paginate the resulted categories list
        paginator_category = Paginator(categories, 12) # display 8 categories per page.
        page_obj_category = paginator_category.get_page(page_number)

    if subcategories:
        # paginate the subcategories list
        paginator_subcategory = Paginator(subcategories, 12) # display 8 subcategories per page.
        page_obj_subcategory = paginator_subcategory.get_page(page_number)

    if products:
        # paginate the resulted products list
        paginator_product = Paginator(products, 12) # display 4 products per page.
        page_obj_product = paginator_product.get_page(page_number)

    context = {'query':query, 
                'companies':page_obj_company, 
                'categories':page_obj_category, 
                'subcategories':page_obj_subcategory,
                'products':page_obj_product, 
            }
    return render(request, 'product/company_list.html', context)


def category_list(request, slug=None):
    """
    Display the company categories list.
    """
    # get the current company
    company = get_object_or_404(Company, slug=slug) 

    # get a queryset of all the categories of the current company
    categories = company.categories.all()

    companies, subcategories, products = None, None, None
    page_obj_company, page_obj_subcategory, page_obj_product = None, None, None
    page_number = request.GET.get('page')

    # Search by company name, category, subcategory, product name, model, or code.
    query = request.GET.get('q')
    if query:
        companies = Company.objects.filter(name__icontains=query) 
        categories = Category.objects.filter(name__icontains=query)
        subcategories = Subcategory.objects.filter(name__icontains=query)
        products = Product.objects.filter(
            Q(name__icontains=query)|
            Q(model__icontains=query)|
            Q(code__icontains=query)
        ).distinct() 

    # paginate the categories list
    paginator_category = Paginator(categories, 12) # display 8 categories per page.
    page_obj_category = paginator_category.get_page(page_number)

    if companies:
        # paginate the companies list
        paginator_company = Paginator(companies, 12) # display 8 companies per page.
        page_obj_company = paginator_company.get_page(page_number)
    
    if subcategories:
        # paginate the subcategories list
        paginator_subcategory = Paginator(subcategories, 12) # display 8 subcategories per page.
        page_obj_subcategory = paginator_subcategory.get_page(page_number)

    if products:
        # paginate the resulted products list
        paginator_product = Paginator(products, 12) # display 4 products per page.
        page_obj_product = paginator_product.get_page(page_number)

    context = { 'query':query,
                'categories':page_obj_category, 
                'company':company, 
                'companies':page_obj_company,
                'subcategories':page_obj_subcategory,
                'products':page_obj_product,
            }
    return render(request, 'product/category_list.html', context)


def subcategory_list(request, comapny_slug=None, category_slug=None):
    """
    Display the company category subcategories list.
    """
    # get the current category
    category = get_object_or_404(Category, slug=category_slug, company__slug=comapny_slug) 

    # get a queryset of all the subcategories of the current category
    subcategories = category.subcategories.all()

    companies, products, categories = None, None, None
    page_obj_company, page_obj_product, page_obj_category = None, None, None
    page_number = request.GET.get('page')

    # Search by company name, category, subcategory, product name, model, or code.
    query = request.GET.get('q')
    if query:
        companies = Company.objects.filter(name__icontains=query) 
        categories = Category.objects.filter(name__icontains=query)
        subcategories = Subcategory.objects.filter(name__icontains=query)
        products = Product.objects.filter(
            Q(name__icontains=query)|
            Q(model__icontains=query)|
            Q(code__icontains=query)
        ).distinct() 

    # paginate the subcategories list
    paginator_subcategory = Paginator(subcategories, 12) # display 8 subcategories per page.
    page_obj_subcategory = paginator_subcategory.get_page(page_number)

    if companies:
        # paginate the companies list
        paginator_company = Paginator(companies, 12) # display 8 companies per page.
        page_obj_company = paginator_company.get_page(page_number)
    
    if categories:
        # paginate the categories list
        paginator_category = Paginator(categories, 12) # display 8 categories per page.
        page_obj_category = paginator_category.get_page(page_number)

    if products:
        # paginate the resulted products list
        paginator_product = Paginator(products, 12) # display 4 products per page.
        page_obj_product = paginator_product.get_page(page_number)

    context = { 'query':query,
                'subcategories':page_obj_subcategory, 
                'category':category, 
                'companies':page_obj_company,
                'categories':page_obj_category,
                'products':page_obj_product,
            }
    return render(request, 'product/subcategory_list.html', context)


def product_list(request, comapny_slug=None, category_slug=None, subcategory_slug=None):
    """
    Display the company category products list.
    """
    # get the current subcategory
    subcategory = get_object_or_404(Subcategory, slug=subcategory_slug, company__slug=comapny_slug, category__slug=category_slug) 

    # get a queryset of all the products of the current category
    products = subcategory.products.all()

    companies, categories, subcategories = None, None, None
    page_obj_company, page_obj_category, page_obj_subcategory = None, None, None
    page_number = request.GET.get('page')

    # Search by company name, category, subcategory, product name, model, or code.
    query = request.GET.get('q')
    if query:
        companies = Company.objects.filter(name__icontains=query) 
        categories = Category.objects.filter(name__icontains=query)
        subcategories = Subcategory.objects.filter(name__icontains=query)
        products = Product.objects.filter(
            Q(name__icontains=query)|
            Q(model__icontains=query)|
            Q(code__icontains=query)
        ).distinct() 

    # paginate the categories list
    paginator_product = Paginator(products, 12) # display 8 products per page.
    page_obj_product = paginator_product.get_page(page_number)
    
    if companies:
        # paginate the companies list
        paginator_company = Paginator(companies, 12) # display 8 companies per page.
        page_obj_company = paginator_company.get_page(page_number)
    
    if categories:
        # paginate the resulted products list
        paginator_category = Paginator(categories, 12) # display 8 categories per page.
        page_obj_category = paginator_category.get_page(page_number)

    if subcategories:
        # paginate the subcategories list
        paginator_subcategory = Paginator(subcategories, 12) # display 8 subcategories per page.
        page_obj_subcategory = paginator_subcategory.get_page(page_number)

    context = { 'query':query,
                'categories':page_obj_category, 
                'subcategory':subcategory, 
                'companies':page_obj_company,
                'subcategories':page_obj_subcategory,
                'products':page_obj_product,
            }
    return render(request, 'product/product_list.html', context)    

product/templates/product/category_list.html
{% extends 'base.html' %}
{% load static %}
{% load product_tags %}

{% block title %}
    <title>Categories</title>
{% endblock title %}

{% block nav-product %}
    active
{% endblock nav-product %}

{% block content %}

<div class="categories">
    <div class="px-5">
        <div class="row no-gutters">

            <!-- Start search-form -->
            {% include 'product/search_form.html' %}
            <!-- End search-form -->

            {% if query %}
                {% if not companies and not categories and not products %}
                    <h2 class="no-results-msg">لم يتم العثور على أى نتائج...</h2>
                {% endif%}
            {% else %}
                {% if not categories %}
                    <div class="products col-12">
                        <div class="row">
                            <div class="col-12 page-title">
                                <h2 class="">منتجات شركة {{ company.name|title }}</h2>
                            </div>
                            <h2 class="no-products-msg">لا توجد منتجات فى هذه الشركة...</h2>
                        </div>  
                    </div>          
                {% endif%}
            {% endif %}


            <!-- Start companies -->
            {% if companies %}
                {% include 'product/search_company.html' %}
            {% endif %}
            <!-- End companies -->

            <!-- Start categories -->
            {% if categories %}
            <div class="col-12 page-title wow flipInX">
                {% if not query %}
                <h2 class="">منتجات شركة {{ company.name|title }}</h2>
                {% else %}
                <h2 class="">الأقسام</h2>
                {% endif %}
            </div>
            <div class="categories-data row no-gutters">
                {% for category in categories %}
                <a href="{% url 'product:product-list' category.company.slug category.slug %}"
                    class="col-12 col-md-4 col-lg-3 category-block px-2 wow {% cycle 'slideInLeft' 'slideInUp' 'slideInRight' 'slideInDown' 'slideInRight'%}">
                    <i class="fas fa-{{ category.icon_type }}"></i>
                    {% if query %}
                    <h3> شركة {{ category.company.name }}</h3>
                    {% endif %}
                    <h3> {{ category.name }}</h3>
                </a>
                {% endfor %}
            </div>
            {% endif %}
            <!-- End categories -->

            <!--Start Products-->
            {% if products %}
                {% include 'product/search_product.html' %}
            {% endif %}
            <!--End Products-->

        </div>
    </div>
</div>


<!--Start Pagination-->
{% if not query and categories.has_other_pages%}
<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
        {% if categories.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ categories.previous_page_number }}">السابق</a>
            </li>
        {% endif %}

        {% for i in categories.paginator.page_range %}
            {% if categories.number == i %}
                <li class="page-item active"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
            {% elif i > categories.number|add:'-3' and i < categories.number|add:'3' %}
                <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
            {% endif %}
        {% endfor %}

        {% if categories.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ categories.next_page_number }}">التالى</a>
            </li>
        {% endif %}
    </ul>
</nav>
{% elif query and companies.has_other_pages or categories.has_other_pages or products.has_other_pages %}
    {% include 'product/search_pagination.html' %}
{% endif %}
<!--End Pagination-->


{% endblock content %}

product/templates/product/company_list.html
{% extends 'base.html' %}
{% load static %}
{% load product_tags %}

{% block title %}
    <title>Companies</title>
{% endblock title %}


{% block nav-product %} 
    active
{% endblock nav-product %}

{% block content %}

<div class="companies">
    <div class="mx-0 mx-md-5">
        <div class="row no-gutters-md">
            
            <!-- Start search-form -->
            {% include 'product/search_form.html' %}
            <!-- End search-form -->

            {% if query %}
                {% if not companies and not categories and not subcategories and not products %}
                    <h2 class="no-results-msg">لم يتم العثور على أى نتائج...</h2>
                {% endif%}
            {% else %}
                {% if not companies %}
                    <div class="products col-12">
                        <div class="row">
                            <h2 class="no-products-msg">لا توجد منتجات ...</h2>
                        </div>  
                    </div>          
                {% endif%}
            {% endif %}

            <!-- Start companies -->
            {% if companies %}
                {% include 'product/search_company.html' %}
            {% endif %}
            <!-- End companies -->

            <!-- Start categories-->
            {% if categories %}
                {% include 'product/search_category.html' %}
            {% endif %}
            <!-- End categories-->

            <!--Start Subcategories-->
            {% if subcategories %}
                {% include 'product/search_subcategory.html' %}
            {% endif %}
            <!--End Subcategories-->
      
            <!--Start Products-->
            {% if products %}
                {% include 'product/search_product.html' %}
            {% endif %}
            <!--End Products-->
        </div>
    </div>
</div>

<!--Start Pagination-->
{% if not query and companies.has_other_pages%}
<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
        {% if companies.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ companies.previous_page_number }}">السابق</a>
        </li>
        {% endif %}

        {% for i in companies.paginator.page_range %}
            {% if companies.number == i %}
                <li class="page-item active"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
            {% elif i > companies.number|add:'-3' and i < companies.number|add:'3' %}
                <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
            {% endif %}
        {% endfor %}

        {% if companies.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ companies.next_page_number }}">التالى</a>
            </li>
        {% endif %}
    </ul>
</nav>
{% elif query and companies.has_other_pages or categories.has_other_pages or subcategories.has_other_pages or products.has_other_pages %}
    {% include 'product/search_pagination.html' %}
{% endif %}
<!--End Pagination-->

{% endblock content%}

product/templates/product/product_list.html
{% extends 'base.html' %}
{% load static %}
{% load product_tags %}

{% block title %}
    <title>Products</title>
{% endblock title %}


{% block nav-product %} 
    active
{% endblock nav-product %}

{% block content %}

<div class="categories">
    <div class="px-0 px-md-5">
        <div class="row no-gutters-md">

            <!-- Start search-form -->
            {% include 'product/search_form.html' %}
            <!-- End search-form -->
            
            {% if query %}
                {% if not companies and not categories and not subcategories and not products %}
                <h2 class="no-results-msg">لم يتم العثور على أى نتائج...</h2>
                {% endif%}
            {% else %}
                {% if not products %}
                <div class="products col-12">
                    <div class="row">
                        <div class="col-12 page-title">
                            <h2 class="">{{ subcategory.name|title }} </h2>
                        </div>
                        <h2 class="no-products-msg">لا توجد منتجات فى هذا القسم...</h2>
                    </div>  
                </div>          
                {% endif%}
            {% endif %}

            <!-- Start companies -->
            {% if companies %}
                {% include 'product/search_company.html' %}
            {% endif %}
            <!-- End companies -->

            <!-- Start categories -->
            {% if categories %}
                {% include 'product/search_category.html' %}
            {% endif %}
            <!-- End categories -->

            <!--Start Subcategories-->
            {% if subcategories %}
                {% include 'product/search_subcategory.html' %}
            {% endif %}
            <!--End Subcategories-->

            <!--Start Products-->
            {% if products and query %}
                {% include 'product/search_product.html' %}
            {% elif products %}
            <!-- Start  products search-->
            <div class="products col-12">
                <div class="row">
                    <div class="col-12 page-title">
                        <h2 class="">{{ subcategory.name|title }} </h2>
                    </div>
                    {% for product in products %}
                    <div class="col-12 col-xl-6">
                        <div class="product">
                            <div class="product-img">
                                <img src="{{ product.image.url }}">
                            </div>
                            <div class="product-data">
                                <h3 class="">
                                    <span class="">المنتج:</span>
                                    <span class="">{{ product.name }}</span>
                                </h3>
                                <p class="model">
                                    <span class="">الطراز:</span>
                                    <span class="">{{ product.model }}</span>
                                </p>
                                <p class="order-code">
                                    <span class="">الكود:</span>
                                    <span class="">{{ product.code }}</span>
                                </p>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
            {% endif %}
            <!-- End  products-->            
        </div>
    </div>
</div>

<!--Start Pagination-->
{% if not query and products.has_other_pages%}
<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
        {% if products.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ products.previous_page_number }}">السابق</a>
            </li>
        {% endif %}
        
        {% for i in products.paginator.page_range %}
            {% if products.number == i %}
                <li class="page-item active"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
            {% elif i > products.number|add:'-3' and i < products.number|add:'3' %}
                <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
            {% endif %}
        {% endfor %}

        {% if products.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ products.next_page_number }}">التالى</a>
            </li>
        {% endif %}
    </ul>
</nav>
{% elif query and companies.has_other_pages or categories.has_other_pages or subcategories.has_other_pages or products.has_other_pages %}
    {% include 'product/search_pagination.html' %}
{% endif %}

<!--End Pagination-->

{% endblock content %}

product/templates/product/search_category.html
<div class="col-12 page-title wow flipInX">
    <h2 class="">الأقسام</h2>
</div>
<div class="categories-data row no-gutters">
    {% for category in categories %}
    <a href="{{ category.get_absloute_url }}" class="col-12 col-md-4 col-lg-3 category-block wow {% cycle 'slideInLeft' 'slideInUp' 'slideInRight' 'slideInDown' 'slideInRight'%} p-3">
        <i class="fas fa-{{ category.icon_type }}"></i>
        <h3> شركة {{ category.company.name|upper }}</h3>
    
        <h3> {{ category.name|title }}</h3>
    </a>
    {% endfor %}
</div>

product/templates/product/search_company.html
<div class="col-12 page-title wow flipInX">
    <h2>الشركات</h2>
</div>
<div class="col-12">
    <div class="row">
        {% for company in companies %}
        <div
            class="col-12 col-md-6 col-xl-3 wow {% cycle 'slideInUp' 'slideInLeft' 'slideInRight' 'slideInLeft' 'slideInDown'%}">
            <div class="company-block">
                <img src="{{ company.image.url }}">
                <h3>{{ company.name|upper }}</h3>
                <a class="btn view-more" href="{{ company.get_absloute_url }}">عرض المزيد</a>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

product/templates/product/search_form.html
<div class="col-12">
    <form action=".">
        <div class="search-section">
            <input type="text" name='q' value='{{ request.GET.q }}' placeholder="ابحث عن شركات أو أقسام أو منتجات">
            <button class="btn btn-secondary" type="submit">بحث</button>
        </div>
    </form>
</div>

product/templates/product/search_product.html
<div class="col-12">
    <div class="row no-gutters">
        <div class="col-12 page-title wow flipInX">
            <h2>المنتجات</h2>
        </div>
        {% for product in products %}
        <div class="col-12 col-xl-6">
            <div class="product">
                <div class="product-img">
                    <img src="{{ product.image.url }}">
                </div>
                <div class="product-data w-100 pl-3 pl-xl-5 py-2">
                    <h3 class="">
                        <span class="">الشركة:</span>
                        <span class="">{{ product.company.name|upper }}</span>
                    </h3>
                    <h3 class="">
                        <span class="">القسم:</span>
                        <span class="">{{ product.category.name|title }}</span>
                    </h3>

                    <h3 class="">
                        <span class="">القسم الفرعى:</span>
                        <span class="">{{ product.subcategory.name|title }}</span>
                    </h3>

                    <h3 class="">
                        <span class="">المنتج:</span>
                        <span class="">{{ product.name|title }}</span>
                    </h3>
                    <p class="model">
                        <span class="">طراز:</span>
                        <span class="">{{ product.model }}</span>
                    </p>
                    <p class="order-code">
                        <span class="">الكود:</span>
                        <span class="">{{ product.code }}</span>
                    </p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

product/templates/product/search_subcategory.html
<div class="col-12 page-title wow flipInX">
    <h2 class="">الأقسام الفرعية</h2>
</div>
<div class="categories-data row no-gutters">
    {% for subcategory in subcategories %}
    <a href="{{ subcategory.get_absloute_url }}" class="col-12 col-md-4 col-lg-3 category-block wow {% cycle 'slideInLeft' 'slideInUp' 'slideInRight' 'slideInDown' 'slideInRight'%} p-3">
        <h3> شركة {{ subcategory.company.name|upper }}</h3>
        <h3> قسم {{ subcategory.category.name|title }}</h3>
        <h3> {{ subcategory.name|title }}</h3>
    </a>
    {% endfor %}
</div>